name: Java CI with Gradle Using GitHub Action oracle-actions/setup-java@v1

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java-release-version: [ '19', 'loom', 'panama', 'valhalla' ]
      fail-fast: false
      max-parallel: 4
    name: Build and test App on JDK ${{ matrix.java-release-version }} ea, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java-release-version }} ${{ matrix.os }}
      uses: oracle-actions/setup-java@v1
      id: download-jdk
      with:
        website: jdk.java.net
        release: ${{ matrix.java-release-version }}
