name: Java CI with Gradle Using GitHub Action setup-java@v3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        java: [ 17.0.4 ]
        distro: [ 'zulu', 'temurin', 'microsoft', 'corretto', 'liberica' ]
      fail-fast: false
      max-parallel: 4
    name: Build and test App on ${{ matrix.distro }} JDK ${{ matrix.java }}, ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up ${{ matrix.distro }} JDK ${{ matrix.java }} ${{ matrix.os }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: ${{ matrix.distro }}
        cache: gradle
    - name: Build with Gradle
      env:
        SOME_PASSWORD: ${{ secrets.MY_PASSWORD }}
        USERNAME: ${{ github.actor }}
        PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: gradle build
